spring:
  datasource:
    password: 123
    url: jdbc:sqlserver://localhost:1433;databaseName=shop;encrypt=true;trustServerCertificate=true;
    username: sa
  jackson:
    date-format: HH:mm:ss dd/MM/yyyy
    time-zone: GMT+7
  #  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

